config/routes.rb
PosDaily::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cms-admin'

  devise_for :users

  resources :merchants
  resources :ttts
  resources :my_trades
	resources :clients do
    patch :del_merchant, :on => :member
    patch :add_merchant, :on => :member
	end

  resources :users do
    post :add, :on => :collection
    patch :del_agent_merchant, :on => :member
    patch :add_agent_merchant, :on => :member
		get :mock, :on => :member
  end

  resources :trades do
    collection do
      post :import
      get :del
      get :submit
      get :rm
    end
  end

	resources :reports do
		collection do
			get :monthly
			get :daily
			post :daily
			get :agents
			post :agents
			get :merchants
			post :merchants
			get :merchant
		end
	end

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :agent_merchants, foreign_key: 'agent_id', class_name: 'Merchant'
	has_many :client_merchants, :foreign_key => 'client_id', :class_name => 'Merchant'
	has_many :clients, foreign_key: 'agent_id', class_name: 'User'
	belongs_to :agent, :class_name => 'User'

	scope :all_agents, -> { where('roles like "%agent%"') }

	def admin?
		self.roles && self.roles.index('admin')
	end
	def agent?
		self.roles && self.roles.index('agent')
	end
end

app/controllers/users_controller.rb
class UsersController < ResourcesController
	before_filter do 
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end

  def add
    params.permit!
    @object = User.new(params[:user])
    if @object.save
      redirect_to users_path
      return
    else
      flash[:error] = @object.errors.full_messages.to_sentence
      @no_log = 1
    end
    render :new
  end
  def add_agent_merchant
    @object = User.find(params[:id])
    @object.agent_merchants << Merchant.find(params[:merchant_id])
  end
  def del_agent_merchant
    @object = User.find(params[:id])
    m = Merchant.find(params[:merchant_id])
    m.agent = nil
    m.save
  end
	def mock
		session[:mock_user] = params[:id]
		redirect_to :controller => :my_trades, :action => :index
	end
end


app/views/users/_form.html.haml
.row
  .col-md-6
    = simple_form_for @object, :html => {:class => 'well form-horizontal'}  do |f|
      = f.error_notification
      = f.input :username
      = f.input :email
      = f.input :roles
      .form-actions
        = f.submit t("save"), :class => "btn btn-primary" 
        = submit_tag t('cancel'), :type => :reset, :class => "btn btn-danger" 
  .col-md-6
    = simple_form_for @object, :html => {:class => 'well form-horizontal'}  do |f|
      = f.error_notification
      = f.input :password
      = f.input :password_confirmation
      .form-actions
        = f.submit t(:save), :class => "btn btn-primary" 
        = submit_tag t(:cancel), :type => :reset, :class => "btn btn-danger" 

= render partial: 'merchants', locals: {user: @object}

app/views/users/_merchants.html.haml
.row#merchants
  .col-md-6
    .list-group
      .list-group-item.active 相关商户
      - user.agent_merchants.each do |m|
        = link_to "#{m.merchant_number} #{m.merchant_name}", del_agent_merchant_user_path(user, merchant_id: m.id), remote: true, method: :patch, class: "list-group-item"
  .col-md-6
    .list-group
      .list-group-item.active 未关联的商户
      - Merchant.free_merchants.each do |m|
        = link_to "#{m.merchant_number} #{m.merchant_name}", add_agent_merchant_user_path(user, merchant_id: m.id), remote: true, method: :patch, class: "list-group-item"


app/views/users/add_agent_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'merchants', locals: {user: @object}) %>");

app/views/users/add_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'merchants', locals: {user: @object}) %>");

app/views/users/del_agent_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'merchants', locals: {user: @object}) %>");


app/views/users/del_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'merchants', locals: {user: @object}) %>");


app/views/users/index.html.haml
%p
  = link_to '新用户', new_user_path, class: "btn btn-default"
= will_paginate @collection
%table.table.table-bordered.table-striped.table-hover
  %tr
    %th ID#
    %th 用户名
    %th Email
    %th 权限
    %th 登陆次数
    %th 当前登录
    %th 上次登录
    %th 创建时间
    %th

  - @collection.each do |u|
    %tr
      %td= u.id
      %td= u.username
      %td= u.email
      %td= u.roles
      %td= u.sign_in_count
      %td
        = u.current_sign_in_at
        %br /
        = u.current_sign_in_ip
        
      %td
        = u.last_sign_in_at
        %br /
        = u.last_sign_in_ip

      %td= u.created_at
      %td
        = link_to 'Edit', edit_user_path(u)
        = link_to '用户数据', mock_user_path(u)
= will_paginate @collection

app/views/users/new.html.haml
%h2 New User
= simple_form_for @object, url: add_users_path, :html => {:class => 'well form-horizontal'}  do |f|
  = f.error_notification
  = f.input :username
  = f.input :email
  = f.input :roles
  = f.input :password
  = f.input :password_confirmation
  .form-actions
    = f.submit "Save", :class => "btn btn-primary" 
    = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" 