config/routes.rb
PosDaily::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cms-admin'

  devise_for :users

  resources :merchants
  resources :ttts
  resources :my_trades
	resources :clients do
    patch :del_merchant, :on => :member
    patch :add_merchant, :on => :member
	end

  resources :users do
    post :add, :on => :collection
    patch :del_agent_merchant, :on => :member
    patch :add_agent_merchant, :on => :member
		get :mock, :on => :member
  end

  resources :trades do
    collection do
      post :import
      get :del
      get :submit
      get :rm
    end
  end

	resources :reports do
		collection do
			get :monthly
			get :daily
			post :daily
			get :agents
			post :agents
			get :merchants
			post :merchants
			get :merchant
		end
	end

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/views/shared/_docs_download.html.haml
- if current_user && current_user.agent?
  %p
    %a.btn.btn-info.btn-lg.btn-block{href: "http://pan.baidu.com/s/1Fut9B", target: '_docs'}
      渠道资料下载（提取码: orrk）

app/views/shared/_main_menu.html.haml
/ Static navbar
.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} 
        = image_tag(("wooul-logo.png"), :alt => "Wooul渠道系统")
        渠道系统
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: (controller?('my_trades') ? 'active' : '')}= link_to '商户数据', my_trades_path
        - if current_user && current_user.agent?
          %li{class: (controller?('clients') ? 'active' : '')}= link_to '我的代理商', clients_path
        - if current_user && current_user.admin?
          %li{class: (controller?('trades') ? 'active' : '')}= link_to '交易数据', trades_path
          %li{class: (controller?('reports') ? 'active' : '')}= link_to '统计报表', reports_path
          %li{class: (controller?('users') ? 'active' : '')}= link_to '用户管理', users_path
        - if current_user && current_user.agent?
          %li 
            %a{href: '/notify'} 公告

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li 
            %strong.welcome 
              欢迎 #{current_user.username}! 
              - if current_user.admin?
                [Admin]
          %li= link_to '退出登录', destroy_user_session_path, method: 'delete'
        - else
          %li 
            %span.pleaselogin 请登录！
    / /.nav-collapse