config/routes.rb
PosDaily::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cms-admin'

  devise_for :users

  resources :merchants
  resources :ttts
  resources :my_trades
	resources :clients do
    patch :del_merchant, :on => :member
    patch :add_merchant, :on => :member
	end

  resources :users do
    post :add, :on => :collection
    patch :del_agent_merchant, :on => :member
    patch :add_agent_merchant, :on => :member
		get :mock, :on => :member
  end

  resources :trades do
    collection do
      post :import
      get :del
      get :submit
      get :rm
    end
  end

	resources :reports do
		collection do
			get :monthly
			get :daily
			post :daily
			get :agents
			post :agents
			get :merchants
			post :merchants
			get :merchant
		end
	end

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
		if current_user.admin? && session[:mock_user]
			@collection = User.find(session[:mock_user]).clients
		else
      @collection = current_user.clients
		end
  end
	def new
		@object = User.new
	end
	def create
		params.permit!
		@object = User.new(params[:user])
		if current_user.admin? && session[:mock_user]
			@object.agent = User.find(session[:mock_user])
		else
  		@object.agent = current_user
		end
		@object.roles = 'client'
		if @object.save
			redirect_to action: :index
			return
		end
		render action: :new
	end
	def edit
		@object = User.find(params[:id])
	end
	def update
		@object = User.find(params[:id])
		params.permit!
		@object.attributes = params[:user]
	  if @object.save
			redirect_to action: :index
		else
			flash[:error] = @object.errors.full_messages.to_sentence
		end
	end
  def add_merchant
    @object = User.find(params[:id])
    @object.client_merchants << Merchant.find(params[:merchant_id])
  end
  def del_merchant
    @object = User.find(params[:id])
    m = Merchant.find(params[:merchant_id])
    m.client = nil
    m.save
  end

  private
    def client_params
      params.require(:client).permit(:trade_date, :merchant_number, :merchant_name, :agent_number, :agnet_name, :terminal_number, :biz_count, :amount, :commission, :actual_amount, :base_commission, :profit, :status)
    end
end

app/views/clients/_admin_mock.html.haml
- if current_user.admin?
  - if session[:mock_user]
    .alert.alert-dismissable.alert-info
      当前查看用户: #{User.find(session[:mock_user]).username}
      = link_to '(更换）', users_path
  - else
    .alert.alert-dismissable.alert-warning
      = link_to '未选择查看用户', users_path

app/views/clients/_client_merchants.html.haml
.row#merchants
  .col-md-6
    .well
      %h4 相关商户
      %ul
        - user.client_merchants.each do |m|
          %li
            = link_to "#{m.merchant_number} #{m.merchant_name}", del_merchant_client_path(user, merchant_id: m.id), remote: true, method: :patch
  .col-md-6
    .well
      %h4 未关联的商户
      %ul
        - user.agent.agent_merchants.free_client_merchants.each do |m|
          %li
            = link_to "#{m.merchant_number} #{m.merchant_name}", add_merchant_client_path(user, merchant_id: m.id), remote: true, method: :patch

app/views/clients/add_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'client_merchants', locals: {user: @object}) %>");

app/views/clients/del_merchant.js.erb
$("#merchants").replaceWith("<%=j render(partial: 'client_merchants', locals: {user: @object}) %>");

app/views/clients/edit.html.haml
= render 'admin_mock'

.btn-group
  = link_to t(:back), @object, class: 'btn btn-default'
  = link_to t(:show), @object, class: 'btn btn-default'

.row
  .col-md-6
    = simple_form_for @object, :html => {:class => 'well form-horizontal'}  do |f|
      = f.error_notification
      = f.input :email
      = f.input :username
      = f.input :roles
      .form-actions
        = f.submit t(:save), :class => "btn btn-primary" 
        = submit_tag t(:cancel), :type => :reset, :class => "btn btn-danger" 
  .col-md-6
    = simple_form_for @object, :html => {:class => 'well form-horizontal'}  do |f|
      = f.error_notification
      = f.input :password
      = f.input :password_confirmation
      .form-actions
        = f.submit t(:save), :class => "btn btn-primary" 
        = submit_tag t(:cancel), :type => :reset, :class => "btn btn-danger" 

= render partial: 'client_merchants', locals: { user: @object }

app/views/clients/index.html.haml
= render 'admin_mock'

%p
  = link_to '新用户', new_client_path, class: "btn btn-default"

%table.table.table-bordered.table-striped.table-hover
  %tr
    %th ID#
    %th 用户名
    %th Email
    %th 权限
    %th 登陆次数
    %th 当前登录
    %th 上次登录
    %th 创建时间
    %th

  - @collection.each do |u|
    %tr
      %td= u.id
      %td= u.username
      %td= u.email
      %td= u.roles
      %td= u.sign_in_count
      %td
        = u.current_sign_in_at
        %br /
        = u.current_sign_in_ip
        
      %td
        = u.last_sign_in_at
        %br /
        = u.last_sign_in_ip

      %td= u.created_at
      %td
        = link_to 'Edit', edit_client_path(u)

app/views/clients/new.html.haml
= render 'admin_mock'
= link_to '返回列表', clients_path

.well
  = simple_form_for @object, :url => clients_path, :html => {:class => 'well form-horizontal'}  do |f|
    = f.error_notification
    = f.input :email
    = f.input :username
    = f.input :roles
    = f.input :password
    = f.input :password_confirmation
    .form-actions
      = f.submit "Save", :class => "btn btn-primary" 
      = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" 

app/views/clients/show.html.haml
.container= render 'admin_mock'

= link_to '返回列表', clients_path
%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th Attribures
      %th Value
  %tbody
    - @object.attributes.each do |attr|
      %tr
        %td= attr[0]
        %td= attr[1]