config/routes.rb
PosDaily::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cms-admin'

  devise_for :users

  resources :merchants
  resources :ttts
  resources :my_trades
	resources :clients do
    patch :del_merchant, :on => :member
    patch :add_merchant, :on => :member
	end

  resources :users do
    post :add, :on => :collection
    patch :del_agent_merchant, :on => :member
    patch :add_agent_merchant, :on => :member
		get :mock, :on => :member
  end

  resources :trades do
    collection do
      post :import
      get :del
      get :submit
      get :rm
    end
  end

	resources :reports do
		collection do
			get :monthly
			get :daily
			post :daily
			get :agents
			post :agents
			get :merchants
			post :merchants
			get :merchant
		end
	end

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  scope :new_import, -> { where(status: 0) }
  scope :published, -> { where(status: 1) }
end

app/controllers/trades_controller.rb
class TradesController < ResourcesController
	before_filter do 
    redirect_to :new_user_session_path unless current_user && current_user.admin?
  end
  def import
    trade_date = params[:trade_date]
    data = params[:import_text]
    lines = data.split(/\n/)
    imp_lines = 0
    lines.each do |line|
      cs = line.split(/[\t]/)
      if cs.length>8 && cs[1].start_with?('826')
        b = Trade.new
        b.trade_date = cs[0].to_date
        b.merchant_number = cs[1].strip
        b.merchant_name = cs[2]
        b.agent_number = ''
        b.agent_name = ''
        b.terminal_number = cs[3]
        b.biz_count = cs[4].to_i
        b.amount = cs[5].to_f
        b.commission = cs[6].to_f
        b.actual_amount = b.amount - b.commission
        b.base_commission = cs[7].to_f
        b.profit = cs[8].to_f
        b.status = 0
        imp_lines += 1
        b.save
      end
    end
    flash[:notice] = "导入#{imp_lines}行数据。"
  end
  def del
    Trade.destroy_all(status: 0)
  end
  def submit
    Trade.new_import.each do |t|
      Merchant.find_or_create_by(merchant_number: t.merchant_number) do |m|
        m.merchant_name = t.merchant_name
        m.status = 1
      end
    end
    Trade.where(status: 0).update_all(status: 1)
  end
  def rm
    dt = params[:dt].to_date
    if dt
      Trade.where(trade_date: dt).destroy_all
    end
    redirect_to trades_path('q[trade_date_gteq]' => dt, 'q[trade_date_lteq]' => dt)
  end

  protected
    def load_collection
      params[:q] ||= {}
      if params[:op] == 'import'
        @q = Trade.new_import.search(params[:q])
      else
        @q = Trade.published.search(params[:q])
      end
      pages = 20
      @collection = @q.result.paginate(:page => params[:page], :per_page => pages)
			@sum ||= @q.result.select('sum(biz_count) biz_count, sum(amount) amount, sum(commission) commission, sum(actual_amount) actual_amount, sum(base_commission) base_commission, sum(profit) profit').first
    end 

  private
    def trade_params
      params.require(:trade).permit(:trade_date, :merchant_number, :merchant_name, :agent_number, :agnet_name, :terminal_number, :biz_count, :amount, :commission, :actual_amount, :base_commission, :profit, :status)
    end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.haml
.container
  = simple_form_for @object, :html => {:class => 'well form-horizontal'}  do |f|
    = f.error_notification
    = f.input :trade_date
    = f.input :merchant_number
    = f.input :merchant_name
    = f.input :agent_number
    = f.input :agent_name
    = f.input :terminal_number
    = f.input :biz_count
    = f.input :amount
    = f.input :commission
    = f.input :actual_amount
    = f.input :base_commission
    = f.input :profit
    = f.input :status, :collection => [["New", 0], ['Done', 1]]
    .form-actions
      = f.submit "Save", :class => "btn btn-primary" 
      = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" 

app/views/trades/del.js.erb
alert('已经清除所有未导入数据！');
location.reload();

app/views/trades/import.js.erb
alert("<%=raw flash[:notice] %>");
<% flash.discard %>
location.reload();

app/views/trades/index.html.haml
- if params[:op] == 'import'
  .btn-group
    = link_to '正式数据', trades_path, class: "btn btn-default"
    = link_to '清空数据', del_trades_path, remote: true, class: "btn btn-default"
    = link_to '提交数据', submit_trades_path, data: {confirm: '数据提交后将不能修改，并会被客户查询到。'}, remote: true, class: "btn btn-default"
    %a.btn.btn-primary{'data-toggle' => "modal", href: "#myModal"} 导入终端交易数据
- else
  = search_form_for @q ,html: {class: "form-inline", role: 'form'} do |f|
    .form-group
      = f.label :trade_date_gteq, '开始日期', class: "sr-only"
      = f.text_field :trade_date_gteq, placeholder: "开始日期", class: "form-control search-ipt-terminal date-picker"
    .form-group
      = f.label :trade_date_lteq, '结束日期', class: "sr-only"
      = f.text_field :trade_date_lteq, placeholder: '结束日期', class: 'form-control search-ipt-terminal date-picker'
    .form-group
      = f.label :merchant_number_cont, '商户编号', class: "sr-only"
      = f.text_field :merchant_number_cont, placeholder: "商户编号", class: "form-control"
    .form-group
      = f.label :merchant_name_cont, '商户名称', class: "sr-only"
      = f.text_field :merchant_name_cont, placeholder: "商户名称", class: "form-control"
    .form-group
      = f.label :terminal_number_cont, '终端号', class: "sr-only"
      = f.text_field :terminal_number_cont, placeholder: "终端号", class: "form-control search-ipt-terminal"
    .form-group
      = f.label :biz_count_gteq, '交易笔数大于', class: "sr-only"
      = f.text_field :biz_count_gteq, placeholder: '交易笔数大于', class: 'form-control search-ipt-terminal'
    = f.submit '查找', class: "btn btn-primary"
    = link_to '导入数据', trades_path(op: 'import'), class: "btn btn-default"
    - if params[:q][:trade_date_gteq] && params[:q][:trade_date_lteq] && params[:q][:trade_date_gteq] == params[:q][:trade_date_lteq]
      - dt = params[:q][:trade_date_gteq].to_date
      = link_to '删除数据', rm_trades_path(dt: dt), class: 'btn btn-danger', data: {confirm: "确认要删除 #{dt} 的数据吗？"}



= will_paginate @collection
%table.table.table-bordered.table-striped.table-hover
  %tr
    %th 交易日期
    %th 商户号 
    %th 商户名称
    %th 终端号
    %th 交易笔数
    %th 交易金额
    %th 交易手续费
    %th 实收金额
    %th 基准手续费
    %th 利润
  %tr.success
    %td{colspan:'4'} 合计
    %td= @sum[:biz_count]
    %td.num= format_dec @sum[:amount]
    %td.num= format_dec @sum[:commission]
    %td.num= format_dec @sum[:actual_amount]
    %td.num= format_dec @sum[:base_commission]
    %td.num= format_dec @sum[:profit]

  - @collection.each do |trade|
    %tr
      %td= trade.trade_date
      %td= trade.merchant_number
      %td= trade.merchant_name
      %td= trade.terminal_number
      %td= trade.biz_count
      %td.num= number_with_delimiter '%.2f' % trade.amount
      %td.num= number_with_delimiter '%.2f' % trade.commission
      %td.num= number_with_delimiter '%.2f' % trade.actual_amount
      %td.num= number_with_delimiter '%.2f' % trade.base_commission
      %td.num= number_with_delimiter '%.2f' % trade.profit

  %tr.success
    %td{colspan:'4'} 合计
    %td= @sum[:biz_count]
    %td.num= format_dec @sum[:amount]
    %td.num= format_dec @sum[:commission]
    %td.num= format_dec @sum[:actual_amount]
    %td.num= format_dec @sum[:base_commission]
    %td.num= format_dec @sum[:profit]
= will_paginate @collection
%br

.modal.fade{id: "myModal", tabindex: "-1", role: "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", 'data-dismiss' => "modal",  'aria-hidden' => "true"} &times;
        %h4.modal-title 导入终端交易数据
      .modal-body
        = form_tag import_trades_path, remote: true do 
          .form-group
            = text_field_tag 'trade_date', Date.today, class: 'form-control', placeholder: '交易日期'
          .form-group
            = text_area_tag 'import_text', '', class: 'form-control', placeholder: '交易时间 | 商户号 | 商户名称 | 终端号 | 笔数 | 交易金额合计 | 手续费金额合计 | 商户基准手续费 | 利润', :rows => 10
      .modal-footer
        %button.btn.btn-default{type: "button", 'data-dismiss' => "modal"} 放弃修改
        %button.btn.btn-primary{:onclick => "submit_dialog_form(this)", :disable_with => "正在处理...."} 保存修改

app/views/trades/submit.js.erb
alert('数据已提交');
location.reload();